/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project2;

import javax.swing.JOptionPane;
/**
 *
 * @author ASUS
 */
public class Coffee extends javax.swing.JFrame {

    /**
     * Creates new form Coffee
     */
    public Coffee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        abc = new javax.swing.JRadioButton();
        golda = new javax.swing.JRadioButton();
        goodday = new javax.swing.JRadioButton();
        nescafe = new javax.swing.JRadioButton();
        kopiko = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        uang = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        sisa = new javax.swing.JTextField();
        next = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(491, 369));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 102));

        jLabel1.setFont(new java.awt.Font("Birch Std", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("COFFEE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(jLabel1))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 53));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project2/pict/abcexo.jpg"))); // NOI18N
        jTabbedPane1.addTab("ABC EXO", jLabel7);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project2/pict/golda2.jpeg"))); // NOI18N
        jTabbedPane1.addTab("Golda", jLabel6);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project2/pict/goodday.jpg"))); // NOI18N
        jTabbedPane1.addTab("Good Day", jLabel5);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project2/pict/images.jpg"))); // NOI18N
        jTabbedPane1.addTab("Nescafe", jLabel4);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project2/pict/kopiko4.jpg"))); // NOI18N
        jTabbedPane1.addTab("Kopiko", jLabel9);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 104, -1));

        abc.setForeground(new java.awt.Color(255, 255, 255));
        abc.setText("ABC EXO Rp.4500");
        abc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abcActionPerformed(evt);
            }
        });
        jPanel1.add(abc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 99, -1, -1));

        golda.setForeground(new java.awt.Color(255, 255, 255));
        golda.setText("Golda Coffee Rp.3000");
        golda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goldaActionPerformed(evt);
            }
        });
        jPanel1.add(golda, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        goodday.setForeground(new java.awt.Color(255, 255, 255));
        goodday.setText("GoodDay Rp,5500");
        goodday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gooddayActionPerformed(evt);
            }
        });
        jPanel1.add(goodday, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 181, -1, -1));

        nescafe.setForeground(new java.awt.Color(255, 255, 255));
        nescafe.setText("Nescafe Rp.6000");
        nescafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nescafeActionPerformed(evt);
            }
        });
        jPanel1.add(nescafe, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 222, -1, -1));

        kopiko.setForeground(new java.awt.Color(255, 255, 255));
        kopiko.setText("Kopiko Rp.6000");
        kopiko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kopikoActionPerformed(evt);
            }
        });
        jPanel1.add(kopiko, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 263, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Insert Your Money");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 79, -1, -1));

        uang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uangActionPerformed(evt);
            }
        });
        jPanel1.add(uang, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 99, 114, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Change");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 142, -1, -1));
        jPanel1.add(sisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 162, 114, -1));

        next.setBackground(new java.awt.Color(255, 255, 255));
        next.setText("Next");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        jPanel1.add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 326, -1, -1));

        clear.setBackground(new java.awt.Color(255, 255, 255));
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel1.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 326, -1, -1));

        cancel.setBackground(new java.awt.Color(255, 255, 255));
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel1.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 326, 76, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uangActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        abc.setSelected(false);
        golda.setSelected(false);
        goodday.setSelected(false);
        nescafe.setSelected(false);
        kopiko.setSelected(false);
        uang.setText("Rp.0");
        sisa.setText("Rp.0");
    }//GEN-LAST:event_clearActionPerformed

    private void abcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abcActionPerformed
        // ABC EXO
        if (abc.isSelected()){
         
            golda.setSelected(false);
            goodday.setSelected(false);
            nescafe.setSelected(false);
            kopiko.setSelected(false);
        
    }                
    }//GEN-LAST:event_abcActionPerformed

    private void goldaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goldaActionPerformed
        // Golda
        if (golda.isSelected()){
         
            abc.setSelected(false);
            goodday.setSelected(false);
            nescafe.setSelected(false);
            kopiko.setSelected(false);
        
    }          
    }//GEN-LAST:event_goldaActionPerformed

    private void gooddayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gooddayActionPerformed
        // TODO add your handling code here:
        if (goodday.isSelected()){
         
            golda.setSelected(false);
            abc.setSelected(false);
            nescafe.setSelected(false);
            kopiko.setSelected(false);
        
    }          
    }//GEN-LAST:event_gooddayActionPerformed

    private void nescafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nescafeActionPerformed
        // TODO add your handling code here:
        if (nescafe.isSelected()){
         
            golda.setSelected(false);
            goodday.setSelected(false);
            abc.setSelected(false);
            kopiko.setSelected(false);
        
    }          
    }//GEN-LAST:event_nescafeActionPerformed

    private void kopikoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kopikoActionPerformed
        // TODO add your handling code here:
        if (kopiko.isSelected()){
         
            golda.setSelected(false);
            goodday.setSelected(false);
            nescafe.setSelected(false);
            abc.setSelected(false);
        
    }          
    }//GEN-LAST:event_kopikoActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        
        new newmenu().setVisible(true);
    }//GEN-LAST:event_cancelActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
        int inputuang = 0;
        inputuang =Integer.parseInt(uang.getText());
        if (abc.isSelected()){
            inputuang = inputuang - 4500;
        }
        else if (golda.isSelected()){
            inputuang = inputuang - 3000;
        }
        else if (goodday.isSelected()){
            inputuang = inputuang - 5500;
        }
        else if (nescafe.isSelected()){
            inputuang = inputuang - 6000;
        }
        else if (kopiko.isSelected()){
            inputuang = inputuang - 6000;
        }
            
            if (inputuang < 0){
                new Coffee().setVisible(true);
            }
            else {
                sisa.setText(Double.toString(inputuang));
                JOptionPane.showMessageDialog(rootPane,"Thank You for Buying In RET's Vending Machine");
            }
    }//GEN-LAST:event_nextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Coffee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Coffee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Coffee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Coffee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Coffee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton abc;
    private javax.swing.JButton cancel;
    private javax.swing.JButton clear;
    private javax.swing.JRadioButton golda;
    private javax.swing.JRadioButton goodday;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton kopiko;
    private javax.swing.JRadioButton nescafe;
    private javax.swing.JButton next;
    private javax.swing.JTextField sisa;
    private javax.swing.JTextField uang;
    // End of variables declaration//GEN-END:variables
}
