/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project2;

/**
 *
 * @author ASUS
 */
public class newmenu extends javax.swing.JFrame {

    /**
     * Creates new form newmenu
     */
    public newmenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        milkpanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        coffeepanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        teapanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cokepanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bgpict = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(0, 0, 0));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        milkpanel.setBackground(new java.awt.Color(0, 0, 204));
        milkpanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        milkpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                milkpanelMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Birch Std", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 51));
        jLabel4.setText("Milk");
        jLabel4.setToolTipText("");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout milkpanelLayout = new javax.swing.GroupLayout(milkpanel);
        milkpanel.setLayout(milkpanelLayout);
        milkpanelLayout.setHorizontalGroup(
            milkpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(milkpanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        milkpanelLayout.setVerticalGroup(
            milkpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        background.add(milkpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 100, 50));

        coffeepanel.setBackground(new java.awt.Color(255, 255, 51));
        coffeepanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        coffeepanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                coffeepanelMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Birch Std", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Coffee");

        javax.swing.GroupLayout coffeepanelLayout = new javax.swing.GroupLayout(coffeepanel);
        coffeepanel.setLayout(coffeepanelLayout);
        coffeepanelLayout.setHorizontalGroup(
            coffeepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coffeepanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        coffeepanelLayout.setVerticalGroup(
            coffeepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        background.add(coffeepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 110, 50));

        teapanel.setBackground(new java.awt.Color(255, 255, 51));
        teapanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        teapanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teapanelMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Birch Std", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("Tea");

        javax.swing.GroupLayout teapanelLayout = new javax.swing.GroupLayout(teapanel);
        teapanel.setLayout(teapanelLayout);
        teapanelLayout.setHorizontalGroup(
            teapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teapanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        teapanelLayout.setVerticalGroup(
            teapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        background.add(teapanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 100, 50));

        cokepanel.setBackground(new java.awt.Color(0, 0, 204));
        cokepanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cokepanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cokepanelMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Birch Std", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Coke");

        javax.swing.GroupLayout cokepanelLayout = new javax.swing.GroupLayout(cokepanel);
        cokepanel.setLayout(cokepanelLayout);
        cokepanelLayout.setHorizontalGroup(
            cokepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cokepanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        cokepanelLayout.setVerticalGroup(
            cokepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        background.add(cokepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, 50));

        bgpict.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project2/pict/pexels-photo-1722177.jpeg"))); // NOI18N
        background.add(bgpict, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        jLabel5.setFont(new java.awt.Font("Birch Std", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 0));
        jLabel5.setText("\"RET's\" Vending Machine");
        background.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 9, -1, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cokepanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cokepanelMouseClicked
        // COKE
        new Soda().setVisible(true);
    }//GEN-LAST:event_cokepanelMouseClicked

    private void teapanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teapanelMouseClicked
        // TEA
         new Tea().setVisible(true);
    }//GEN-LAST:event_teapanelMouseClicked

    private void coffeepanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coffeepanelMouseClicked
        // COFFEE
         new Coffee().setVisible(true);
    }//GEN-LAST:event_coffeepanelMouseClicked

    private void milkpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_milkpanelMouseClicked
        // MILK
         new Milk().setVisible(true);
    }//GEN-LAST:event_milkpanelMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newmenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel bgpict;
    private javax.swing.JPanel coffeepanel;
    private javax.swing.JPanel cokepanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel milkpanel;
    private javax.swing.JPanel teapanel;
    // End of variables declaration//GEN-END:variables
}
