/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project2;

import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class Soda extends javax.swing.JFrame {

    /**
     * Creates new form Soda
     */
    public Soda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bodyup = new javax.swing.JPanel();
        judul = new javax.swing.JLabel();
        backgroundpanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        next = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        pepsipilihan = new javax.swing.JRadioButton();
        colapilihan = new javax.swing.JRadioButton();
        spritepilihan = new javax.swing.JRadioButton();
        fayrouzpilihan = new javax.swing.JRadioButton();
        bigcolapilihan = new javax.swing.JRadioButton();
        uang = new javax.swing.JTextField();
        sisa = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        colalabel = new javax.swing.JLabel();
        bigcolalabel = new javax.swing.JLabel();
        fayrouzlabel = new javax.swing.JLabel();
        pepsilabel = new javax.swing.JLabel();
        spritelabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bodyup.setBackground(new java.awt.Color(0, 0, 153));
        bodyup.setForeground(new java.awt.Color(255, 255, 51));

        judul.setFont(new java.awt.Font("Birch Std", 0, 48)); // NOI18N
        judul.setForeground(new java.awt.Color(255, 255, 102));
        judul.setText("Coke");

        javax.swing.GroupLayout bodyupLayout = new javax.swing.GroupLayout(bodyup);
        bodyup.setLayout(bodyupLayout);
        bodyupLayout.setHorizontalGroup(
            bodyupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyupLayout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(judul)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bodyupLayout.setVerticalGroup(
            bodyupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(369, 369, 369))
        );

        backgroundpanel.setBackground(new java.awt.Color(255, 255, 102));

        jLabel1.setText("Insert Your Money");

        jLabel2.setText("Change");

        next.setBackground(new java.awt.Color(255, 255, 255));
        next.setText("Next");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        clear.setBackground(new java.awt.Color(255, 255, 255));
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        cancel.setBackground(new java.awt.Color(255, 255, 255));
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        pepsipilihan.setBackground(new java.awt.Color(255, 255, 255));
        pepsipilihan.setText("Pepsi Rp.4500");
        pepsipilihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pepsipilihanActionPerformed(evt);
            }
        });

        colapilihan.setBackground(new java.awt.Color(255, 255, 255));
        colapilihan.setText("CocaCola Rp.4000");
        colapilihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colapilihanActionPerformed(evt);
            }
        });

        spritepilihan.setBackground(new java.awt.Color(255, 255, 255));
        spritepilihan.setText("Sprite Rp.4000");
        spritepilihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spritepilihanActionPerformed(evt);
            }
        });

        fayrouzpilihan.setBackground(new java.awt.Color(255, 255, 255));
        fayrouzpilihan.setText("Fayrouz Rp.6000");
        fayrouzpilihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fayrouzpilihanActionPerformed(evt);
            }
        });

        bigcolapilihan.setBackground(new java.awt.Color(255, 255, 255));
        bigcolapilihan.setText("Big Cola Rp.3500");
        bigcolapilihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bigcolapilihanActionPerformed(evt);
            }
        });

        uang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uangActionPerformed(evt);
            }
        });

        sisa.setEditable(false);

        colalabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project2/pict/cola2.jpg"))); // NOI18N
        jTabbedPane1.addTab("Coca Cola", colalabel);

        bigcolalabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project2/pict/big cola2.jpg"))); // NOI18N
        jTabbedPane1.addTab("Big Cola", bigcolalabel);

        fayrouzlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project2/pict/fayrouz2.jpg"))); // NOI18N
        jTabbedPane1.addTab("Fayrouz", fayrouzlabel);

        pepsilabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project2/pict/pepsi2.jpg"))); // NOI18N
        jTabbedPane1.addTab("Pepsi", pepsilabel);

        spritelabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project2/pict/sprite2.jpg"))); // NOI18N
        jTabbedPane1.addTab("Sprite", spritelabel);

        javax.swing.GroupLayout backgroundpanelLayout = new javax.swing.GroupLayout(backgroundpanel);
        backgroundpanel.setLayout(backgroundpanelLayout);
        backgroundpanelLayout.setHorizontalGroup(
            backgroundpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundpanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(backgroundpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundpanelLayout.createSequentialGroup()
                        .addGroup(backgroundpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fayrouzpilihan)
                            .addComponent(bigcolapilihan))
                        .addGap(0, 182, Short.MAX_VALUE))
                    .addGroup(backgroundpanelLayout.createSequentialGroup()
                        .addGroup(backgroundpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundpanelLayout.createSequentialGroup()
                                .addComponent(pepsipilihan)
                                .addGap(61, 61, 61)
                                .addGroup(backgroundpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(uang, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sisa, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(backgroundpanelLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(10, 10, 10))))
                            .addComponent(spritepilihan))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(backgroundpanelLayout.createSequentialGroup()
                        .addComponent(colapilihan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(63, 63, 63))))
            .addGroup(backgroundpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(clear)
                .addGap(44, 44, 44)
                .addComponent(next)
                .addContainerGap())
        );
        backgroundpanelLayout.setVerticalGroup(
            backgroundpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundpanelLayout.createSequentialGroup()
                .addGroup(backgroundpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundpanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(2, 2, 2)
                        .addGroup(backgroundpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pepsipilihan)
                            .addComponent(uang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addComponent(sisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundpanelLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(backgroundpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(colapilihan)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(spritepilihan)
                        .addGap(18, 18, 18)
                        .addComponent(fayrouzpilihan)
                        .addGap(18, 18, 18)
                        .addComponent(bigcolapilihan))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundpanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(backgroundpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel)
                    .addComponent(next)
                    .addComponent(clear))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(backgroundpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bodyup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(bodyup, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(backgroundpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pepsipilihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pepsipilihanActionPerformed
        // PEPSI
        if (pepsipilihan.isSelected()){
         
            spritepilihan.setSelected(false);
            bigcolapilihan.setSelected(false);
            colapilihan.setSelected(false);
            fayrouzpilihan.setSelected(false);
        }
    }//GEN-LAST:event_pepsipilihanActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        //CLEAR
        colapilihan.setSelected(false);
        spritepilihan.setSelected(false);
        bigcolapilihan.setSelected(false);
        pepsipilihan.setSelected(false);
        fayrouzpilihan.setSelected(false);
        uang.setText("Rp.0");
        sisa.setText("Rp.0");
        
    
    }//GEN-LAST:event_clearActionPerformed

    private void bigcolapilihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bigcolapilihanActionPerformed
        //BIG COLA
        if (bigcolapilihan.isSelected()){
         
            spritepilihan.setSelected(false);
            pepsipilihan.setSelected(false);
            colapilihan.setSelected(false);
            fayrouzpilihan.setSelected(false);
        }
    }//GEN-LAST:event_bigcolapilihanActionPerformed

    private void colapilihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colapilihanActionPerformed
        // COCACOLA
        if (colapilihan.isSelected()){
         
            spritepilihan.setSelected(false);
            bigcolapilihan.setSelected(false);
            pepsipilihan.setSelected(false);
            fayrouzpilihan.setSelected(false);
        }
    }//GEN-LAST:event_colapilihanActionPerformed

    private void spritepilihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spritepilihanActionPerformed
        //SPRITE
        if (spritepilihan.isSelected()){
         
            pepsipilihan.setSelected(false);
            bigcolapilihan.setSelected(false);
            colapilihan.setSelected(false);
            fayrouzpilihan.setSelected(false);
        }
    }//GEN-LAST:event_spritepilihanActionPerformed

    private void fayrouzpilihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fayrouzpilihanActionPerformed
        // FAYROUZ
        if (fayrouzpilihan.isSelected()){
         
            spritepilihan.setSelected(false);
            bigcolapilihan.setSelected(false);
            colapilihan.setSelected(false);
            pepsipilihan.setSelected(false);
        }
    }//GEN-LAST:event_fayrouzpilihanActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
        int inputuang = 0;
        inputuang =Integer.parseInt(uang.getText());
        if (colapilihan.isSelected()){
            inputuang = inputuang - 4000;
        }
        else if (spritepilihan.isSelected()){
            inputuang = inputuang - 4000;
        }
        else if (bigcolapilihan.isSelected()){
            inputuang = inputuang - 3500;
        }
        else if (pepsipilihan.isSelected()){
            inputuang = inputuang - 4500;
        }
        else if (fayrouzpilihan.isSelected()){
            inputuang = inputuang - 6000;
        }
            
            if (inputuang < 0){
                new Soda().setVisible(true);
            }
            else {
                sisa.setText(Double.toString(inputuang));
                JOptionPane.showMessageDialog(rootPane,"Thank You for Buying In RET's Vending Machine");
            }
    }//GEN-LAST:event_nextActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // CANCEL 
        new newmenu().setVisible(true);
    }//GEN-LAST:event_cancelActionPerformed

    private void uangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Soda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Soda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Soda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Soda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Soda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundpanel;
    private javax.swing.JLabel bigcolalabel;
    private javax.swing.JRadioButton bigcolapilihan;
    private javax.swing.JPanel bodyup;
    private javax.swing.JButton cancel;
    private javax.swing.JButton clear;
    private javax.swing.JLabel colalabel;
    private javax.swing.JRadioButton colapilihan;
    private javax.swing.JLabel fayrouzlabel;
    private javax.swing.JRadioButton fayrouzpilihan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel judul;
    private javax.swing.JButton next;
    private javax.swing.JLabel pepsilabel;
    private javax.swing.JRadioButton pepsipilihan;
    private javax.swing.JTextField sisa;
    private javax.swing.JLabel spritelabel;
    private javax.swing.JRadioButton spritepilihan;
    private javax.swing.JTextField uang;
    // End of variables declaration//GEN-END:variables
}
