/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project2;

import javax.swing.JOptionPane;
/**
 *
 * @author ASUS
 */
public class Tea extends javax.swing.JFrame {

    /**
     * Creates new form Tea
     */
    public Tea() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bg = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nugreentealabel = new javax.swing.JTabbedPane();
        tehkotaklabel = new javax.swing.JLabel();
        javalabel = new javax.swing.JLabel();
        bbotollabel = new javax.swing.JLabel();
        pucuklabel = new javax.swing.JLabel();
        greentealabel = new javax.swing.JLabel();
        kotak = new javax.swing.JRadioButton();
        pucuk = new javax.swing.JRadioButton();
        sosro = new javax.swing.JRadioButton();
        tehjava = new javax.swing.JRadioButton();
        greentea = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        uang = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        sisa = new javax.swing.JTextField();
        next = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(491, 369));

        bg.setBackground(new java.awt.Color(0, 0, 102));

        jPanel3.setBackground(new java.awt.Color(255, 255, 102));
        jPanel3.setPreferredSize(new java.awt.Dimension(269, 429));

        jLabel1.setFont(new java.awt.Font("Birch Std", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("TEA");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(203, 203, 203))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        nugreentealabel.setBackground(new java.awt.Color(255, 255, 255));

        tehkotaklabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project2/pict/kotak2.png"))); // NOI18N
        nugreentealabel.addTab("Teh Kotak", tehkotaklabel);

        javalabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project2/pict/java2.jpg"))); // NOI18N
        nugreentealabel.addTab("Teh Javana", javalabel);

        bbotollabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project2/pict/sosro2.jpg"))); // NOI18N
        nugreentealabel.addTab("Teh Botol", bbotollabel);

        pucuklabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project2/pict/pucuk2.jpg"))); // NOI18N
        nugreentealabel.addTab("Teh Pucuk Harum", pucuklabel);

        greentealabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project2/pict/nct tae4.png"))); // NOI18N
        nugreentealabel.addTab("Nu Green Tea", greentealabel);

        kotak.setForeground(new java.awt.Color(255, 255, 255));
        kotak.setText("Teh Kotak Rp.4500");
        kotak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kotakActionPerformed(evt);
            }
        });

        pucuk.setForeground(new java.awt.Color(255, 255, 255));
        pucuk.setText("Teh Pucuk Rp.3000");
        pucuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pucukActionPerformed(evt);
            }
        });

        sosro.setForeground(new java.awt.Color(255, 255, 255));
        sosro.setText("Teh Botol Sosro Rp.6000");
        sosro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sosroActionPerformed(evt);
            }
        });

        tehjava.setForeground(new java.awt.Color(255, 255, 255));
        tehjava.setText("Teh Java Rp.3500");
        tehjava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tehjavaActionPerformed(evt);
            }
        });

        greentea.setBackground(new java.awt.Color(255, 255, 255));
        greentea.setForeground(new java.awt.Color(255, 255, 255));
        greentea.setText("Nu Green Tea Rp.5000");
        greentea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greenteaActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Insert Your Money");

        uang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uangActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Change");

        sisa.setEditable(false);

        next.setBackground(new java.awt.Color(255, 255, 255));
        next.setText("Next");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        clear.setBackground(new java.awt.Color(255, 255, 255));
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        cancel.setBackground(new java.awt.Color(255, 255, 255));
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(clear)
                .addGap(84, 84, 84)
                .addComponent(next)
                .addContainerGap())
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(nugreentealabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sosro)
                                    .addComponent(greentea))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(kotak)
                                    .addComponent(pucuk)
                                    .addComponent(tehjava))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addComponent(uang, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap())
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                                        .addComponent(sisa, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(82, 82, 82))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(50, 50, 50))))))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kotak)
                            .addComponent(uang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pucuk))
                        .addGap(21, 21, 21)
                        .addComponent(tehjava)
                        .addGap(18, 18, 18)
                        .addComponent(sosro)
                        .addGap(18, 18, 18)
                        .addComponent(greentea)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(nugreentealabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(next)
                    .addComponent(clear)
                    .addComponent(cancel))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pucukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pucukActionPerformed
        // STRAWBERRY
        if (pucuk.isSelected()){
         
            sosro.setSelected(false);
            tehjava.setSelected(false);
            greentea.setSelected(false);
            kotak.setSelected(false);
        }
    }//GEN-LAST:event_pucukActionPerformed

    private void uangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uangActionPerformed

    private void kotakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kotakActionPerformed
        // COCONUT
        if (kotak.isSelected()){
         
            sosro.setSelected(false);
            tehjava.setSelected(false);
            greentea.setSelected(false);
            pucuk.setSelected(false);
        }
    }//GEN-LAST:event_kotakActionPerformed

    private void sosroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sosroActionPerformed
        // KETANHITAM
        if (sosro.isSelected()){
         
            kotak.setSelected(false);
            tehjava.setSelected(false);
            greentea.setSelected(false);
            pucuk.setSelected(false);
        }
    }//GEN-LAST:event_sosroActionPerformed

    private void tehjavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tehjavaActionPerformed
        // LOWFAT
        if (tehjava.isSelected()){
         
            sosro.setSelected(false);
            kotak.setSelected(false);
            greentea.setSelected(false);
            pucuk.setSelected(false);
        }
    }//GEN-LAST:event_tehjavaActionPerformed

    private void greenteaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greenteaActionPerformed
        // MILO
        if (greentea.isSelected()){
         
            sosro.setSelected(false);
            tehjava.setSelected(false);
            kotak.setSelected(false);
            pucuk.setSelected(false);
        }
    }//GEN-LAST:event_greenteaActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // CANCEL
        //new Tea().setVisible(true); 
        new newmenu().setVisible(true);
    }//GEN-LAST:event_cancelActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // CLEAR
        kotak.setSelected(false);
        pucuk.setSelected(false);
        sosro.setSelected(false);
        tehjava.setSelected(false);
        greentea.setSelected(false);
        uang.setText("Rp.0");
        sisa.setText("Rp.0");
    }//GEN-LAST:event_clearActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // NEXT
        int inputuang = 0;
        inputuang =Integer.parseInt(uang.getText());
        if (kotak.isSelected()){
            inputuang = inputuang - 4500;
        }
        else if (pucuk.isSelected()){
            inputuang = inputuang - 3000;
        }
        else if (sosro.isSelected()){
            inputuang = inputuang - 6000;
        }
        else if (tehjava.isSelected()){
            inputuang = inputuang - 3500;
        }
        else if (greentea.isSelected()){
            inputuang = inputuang - 500;
        }
            
            if (inputuang < 0){
                new Tea().setVisible(true);
            }
            else {
                sisa.setText(Double.toString(inputuang));
                JOptionPane.showMessageDialog(rootPane,"Thank You for Buying In RET's Vending Machine");
            }
    }//GEN-LAST:event_nextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Tea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bbotollabel;
    private javax.swing.JPanel bg;
    private javax.swing.JButton cancel;
    private javax.swing.JButton clear;
    private javax.swing.JRadioButton greentea;
    private javax.swing.JLabel greentealabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel javalabel;
    private javax.swing.JRadioButton kotak;
    private javax.swing.JButton next;
    private javax.swing.JTabbedPane nugreentealabel;
    private javax.swing.JRadioButton pucuk;
    private javax.swing.JLabel pucuklabel;
    private javax.swing.JTextField sisa;
    private javax.swing.JRadioButton sosro;
    private javax.swing.JRadioButton tehjava;
    private javax.swing.JLabel tehkotaklabel;
    private javax.swing.JTextField uang;
    // End of variables declaration//GEN-END:variables
}
